services:
  localstack:
    image: localstack/localstack:3.1.0
    environment:
      - IMAGE_NAME=localstack/localstack:3.1.0
      - SERVICES=sns,sqs
      - DEBUG=0
      - DISABLE_CORS_CHECKS=1
      - PARITY_AWS_ACCESS_KEY_ID=1
    ports:
      - '4566:4566'
      - '4570-4597:4570-4597'
  awscli:
      image: amazon/aws-cli:2.15.18
      depends_on:
        - localstack
      environment:
        - AWS_DEFAULT_REGION=eu-west-1
        - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
        - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        - AWS_ENDPOINT_URL=http://localstack:4566
        - AWS_DEFAULT_OUTPUT=table
      entrypoint: /bin/sh -c
      command: >
        "
            sleep 15s
            aws sqs create-queue --queue-name savvyio-commands --attributes FifoQueue=false,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name savvyio-commands.fifo --attributes FifoQueue=true,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name newtonsoft-savvyio-commands --attributes FifoQueue=false,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name newtonsoft-savvyio-commands.fifo --attributes FifoQueue=true,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name savvyio-events --attributes FifoQueue=false,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name savvyio-events.fifo --attributes FifoQueue=true,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name newtonsoft-savvyio-events --attributes FifoQueue=false,ContentBasedDeduplication=false
            aws sqs create-queue --queue-name newtonsoft-savvyio-events.fifo --attributes FifoQueue=true,ContentBasedDeduplication=false
            aws sns create-topic --name member-events-one --attributes FifoTopic=false,ContentBasedDeduplication=false
            aws sns create-topic --name member-events-one.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false
            aws sns create-topic --name member-events-many --attributes FifoTopic=false,ContentBasedDeduplication=false
            aws sns create-topic --name member-events-many.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false
            aws sns create-topic --name newtonsoft-member-events-one --attributes FifoTopic=false,ContentBasedDeduplication=false
            aws sns create-topic --name newtonsoft-member-events-one.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false
            aws sns create-topic --name newtonsoft-member-events-many --attributes FifoTopic=false,ContentBasedDeduplication=false
            aws sns create-topic --name newtonsoft-member-events-many.fifo --attributes FifoTopic=true,ContentBasedDeduplication=false
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:member-events-one --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:savvyio-events --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:member-events-many --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:savvyio-events --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:member-events-one.fifo --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:savvyio-events.fifo --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:member-events-many.fifo --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:savvyio-events.fifo --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:newtonsoft-member-events-one --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:newtonsoft-savvyio-events --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:newtonsoft-member-events-many --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:newtonsoft-savvyio-events --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:newtonsoft-member-events-one.fifo --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:newtonsoft-savvyio-events.fifo --attributes RawMessageDelivery=true
            aws sns subscribe --topic-arn arn:aws:sns:eu-west-1:000000000000:newtonsoft-member-events-many.fifo --protocol sqs --notification-endpoint arn:aws:sqs:eu-west-1:000000000000:newtonsoft-savvyio-events.fifo --attributes RawMessageDelivery=true
        "