parameters:
  - name: SelfHosted
    default: false
    values:
      - true
      - false
  - name: LinuxVmImage
    default: ubuntu-20.04
    values:
      - ubuntu-20.04
  - name: WindowsVmImage
    default: windows-2019
    values:
      - windows-2019