name: $(DayOfYear)$(Rev:rr)
trigger:
  branches:
    include:
    - development
  paths:
    exclude:
    - .azure
    - .docfx
    - .github
    - .nuget
    - LICENSE.md
    - README.md

variables:
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1
  - name: PIPELINES_SELF_HOSTED
    value: false
  - name: PIPELINES_WINDOWS_VM_IMAGE
    value: windows-2022
  - name: PIPELINES_LINUX_VM_IMAGE
    value: ubuntu-20.04

stages:
  - ${{ if endsWith(variables['build.sourceBranch'], 'development') }}:
    - template: stages/development.yml
  - ${{ if endsWith(variables['build.sourceBranch'], 'release') }}:
    - template: stages/staging.yml
  - ${{ if endsWith(variables['build.sourceBranch'], 'master') }}:
    - template: stages/production.yml
  - ${{ if eq(variables['build.reason'], 'PullRequest') }}:
    - template: stages/pullrequest.yml