steps:
  - task: DockerCompose@0
    displayName: 'Spin up LocalStack for unit/integration test'
    inputs:
      containerregistrytype: 'Container Registry'
      dockerComposeFile: '**/docker-compose.yml'
      dockerComposeCommand: "up -d"
      action: 'Run a Docker Compose command'