stages:
  - stage: BuildDevelopment
    displayName: 'Build for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Debug'
      - name: SelfHosted
        value: false
      - name: LinuxVmImage
        value: 'ubuntu-20.04'
      - name: WindowsVmImage
        value: 'windows-2019'
    jobs:
    - template: ../jobs/build-development.yml

  - stage: UpdateBuildNumber
    displayName: 'Updating BUILD_BUILDNUMBER for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    dependsOn: BuildDevelopment
    jobs:
    - template: ../jobs/finalization.yml

  - stage: DeployDevelopment
    displayName: 'Deployment for development branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'development'))
    dependsOn: UpdateBuildNumber
    variables:
    - group: BuildSecrets
    jobs:
    - template: ../jobs/deployment-development.yml