stages:
  - stage: BuildMaster
    displayName: 'Build for master branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'master'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: ../jobs/build-production.yml

  - stage: UpdateBuildNumber
    displayName: 'Updating BUILD_BUILDNUMBER for master branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'master'))
    dependsOn: BuildMaster
    jobs:
    - template: ../jobs/finalization.yml

  - stage: DeployMaster
    displayName: 'Deployment for master branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'master'))
    dependsOn: UpdateBuildNumber
    variables:
    - group: BuildSecrets
    jobs:
    - template: ../jobs/deployment-production.yml