stages:
  - stage: BuildMaster
    displayName: 'Build for main branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    variables:
      - group: BuildSecrets
      - name: BuildSource
        value: 'src'
      - name: BuildConfiguration
        value: 'Release'
    jobs:
    - template: ../jobs/build-production.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: UpdateBuildNumber
    displayName: 'Updating BUILD_BUILDNUMBER for main branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    dependsOn: BuildMaster
    jobs:
    - template: ../jobs/finalization.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}

  - stage: DeployMaster
    displayName: 'Deployment for main branch'
    condition: and(succeeded(), endsWith(variables['build.sourceBranch'], 'main'))
    dependsOn: UpdateBuildNumber
    variables:
    - group: BuildSecrets
    jobs:
    - template: ../jobs/deployment-production.yml
      parameters:
        selfHosted: ${{ parameters.selfHosted }}
        linuxVmImage: ${{ parameters.linuxVmImage }}
        windowsVmImage: ${{ parameters.windowsVmImage }}