jobs:
  - job: BuildDotNet6_0
    displayName: 'Master branch (net6.0, build)'
    timeoutInMinutes: 60
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(PIPELINES_WINDOWS_VM_IMAGE)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(PIPELINES_WINDOWS_VM_IMAGE)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/publish-artifact.yml

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for Production'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(PIPELINES_WINDOWS_VM_IMAGE)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(PIPELINES_WINDOWS_VM_IMAGE)
    variables:
      - name: ArtifactPackageName
        value: 'Production'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactPackages:
          - "net6.0"