jobs:
  - job: BuildDotNet6_0
    displayName: 'PR (build, test)'
    timeoutInMinutes: 90
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build_and_Test:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/install-reportgenerator.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/unit-test.yml
    - template: ../steps/publish-artifact.yml