jobs:
  - job: BuildDotNet7_0
    displayName: 'Release branch (net7, build, test)'
    timeoutInMinutes: 90
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build_Test_and_Package:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net7.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/install-reportgenerator.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net7_0.yml
    - template: ../steps/unit-test.yml
    - template: ../steps/publish-artifact.yml

  - job: BuildDotNet6_0
    displayName: 'Release branch (net6, build)'
    timeoutInMinutes: 90
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: ${{ parameters.linuxVmImage }}
        Windows_Build_Test_and_Package:
          imageName: ${{ parameters.windowsVmImage }}
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/publish-artifact.yml

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet7_0
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for RC'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(parameters.selfHosted, 'true') }}:
        name: ${{ parameters.windowsVmImage }}
      ${{ if eq(parameters.selfHosted, 'false') }}:
        vmImage: ${{ parameters.windowsVmImage }}
    variables:
      - name: ArtifactPackageName
        value: 'ReleaseCandidate'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactPackages:
          - "net7.0"
          - "net6.0"