jobs:
  - job: BuildDotNet6_0
    displayName: 'Development branch (net6, build, test, code-coverage, code-analysis)'
    timeoutInMinutes: 120
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: $(PipelinesLinuxVmImage)
        Windows_Build_Test_and_Package:
          imageName: $(PipelinesWindowsVmImage)
    pool:
      ${{ if eq(variables.PipelinesSelfHosted, 'true') }}:
        name: $(imageName)
      ${{ if eq(variables.PipelinesSelfHosted, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/install-reportgenerator.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/sonarcloud-prepare.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/unit-test.yml
    - template: ../steps/codecov.yml
    - template: ../steps/sonarcloud-finalize.yml
    - template: ../steps/publish-artifact.yml

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for Preview'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(PipelinesWindowsVmImage)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(PipelinesWindowsVmImage)
    variables:
      - name: ArtifactPackageName
        value: 'Preview'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactPackages:
          - "net6.0"