jobs:
  - job: BuildDotNet6_0
    displayName: 'Release branch (net6, build, test)'
    timeoutInMinutes: 90
    strategy:
      matrix:
        Linux_Build_and_Test:
          imageName: $(PIPELINES_LINUX_VM_IMAGE)
        Windows_Build_Test_and_Package:
          imageName: $(PIPELINES_WINDOWS_VM_IMAGE)
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(imageName)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(imageName)
    variables:
      - name: DotnetBuildName
        value: 'net6.0'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/install-reportgenerator.yml
    - template: ../steps/download-snk.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/restore.yml
    - template: ../steps/build-net6_0.yml
    - template: ../steps/unit-test.yml
    - template: ../steps/publish-artifact.yml

  - job: PublishBuildArtifacts
    condition: succeeded()
    dependsOn:
    - BuildDotNet6_0
    displayName: 'Store NuGet Packages for RC'
    timeoutInMinutes: 30
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(PIPELINES_WINDOWS_VM_IMAGE)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(PIPELINES_WINDOWS_VM_IMAGE)
    variables:
      - name: ArtifactPackageName
        value: 'ReleaseCandidate'
    steps:
    - template: ../steps/dotnet.yml
    - template: ../steps/install-minvertool.yml
    - template: ../steps/minverversion-override.yml
    - template: ../steps/publish-nuget.yml
      parameters:
        artifactPackages:
          - "net6.0"