jobs:
  - deployment: 'CD'
    displayName: 'Preview: release to private NuGet Feed'
    environment: 'Development'
    pool:
      ${{ if eq(variables.PipelinesSelfHosted, 'true') }}:
        name: $(PipelinesLinuxVmImage)
      ${{ if eq(variables.PipelinesSelfHosted, 'false') }}:
        vmImage: $(PipelinesLinuxVmImage)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Preview'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://nuget.codebelt.net/v3/index.json'
              inputs:
                command: push
                packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;$(System.DefaultWorkingDirectory)/**/*.snupkg'
                nuGetFeedType: external
                publishFeedCredentials: 'Codebelt-Nuget'