jobs:
  - deployment: 'CD'
    displayName: 'RC: release to public NuGet Feed'
    environment: 'Staging'
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(PIPELINES_LINUX_VM_IMAGE)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(PIPELINES_LINUX_VM_IMAGE)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'ReleaseCandidate'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://api.nuget.org/v3/index.json'
              inputs:
                command: custom
                arguments: 'push $(System.DefaultWorkingDirectory)/**/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $(nuget-official-apikey) -SkipDuplicate'