parameters:
  - name: SelfHosted
    default: false
    type: boolean
  - name: LinuxVmImage
    default: ubuntu-20.04
    type: string
    values:
      - ubuntu-20.04
  - name: WindowsVmImage
    default: windows-2019
    type: string
    values:
      - windows-2019
jobs:
  - deployment: CD
    condition: eq(parameters.SelfHosted, 'false')
    displayName: 'Preview: release to private NuGet Feed'
    environment: 'Development'
    pool:
      vmImage: ${{ parameters.LinuxVmImage }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Preview'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://nuget.codebelt.net/v3/index.json'
              inputs:
                command: push
                packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;$(System.DefaultWorkingDirectory)/**/*.snupkg'
                nuGetFeedType: external
                publishFeedCredentials: 'Codebelt-Nuget'


  - deployment: CD_SelfHosted
    condition: eq(parameters.SelfHosted, 'true')
    displayName: 'Preview: release to private NuGet Feed (self-hosted)'
    environment: 'Development'
    pool:
      name: ${{ parameters.LinuxVmImage }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: 'Download the build artifacts'
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Preview'
                downloadPath: '$(System.DefaultWorkingDirectory)'

            - task: NuGetCommand@2
              displayName: 'Publish NuGet Packages to https://nuget.codebelt.net/v3/index.json'
              inputs:
                command: push
                packagesToPush: '$(System.DefaultWorkingDirectory)/**/*.nupkg;$(System.DefaultWorkingDirectory)/**/*.snupkg'
                nuGetFeedType: external
                publishFeedCredentials: 'Codebelt-Nuget'