jobs:
  - job: 'Finalizer'
    displayName: 'Update BUILD_NUMBER (finalizer)'
    timeoutInMinutes: 15
    pool:
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'true') }}:
        name: $(variables.PIPELINES_LINUX_VM_IMAGE)
      ${{ if eq(variables.PIPELINES_SELF_HOSTED, 'false') }}:
        vmImage: $(variables.PIPELINES_LINUX_VM_IMAGE)
    steps:
      - template: ../steps/dotnet.yml
      - template: ../steps/install-minvertool.yml
      - template: ../steps/minverversion-override.yml
      - template: ../steps/update-buildnumber.yml