parameters:
  - name: SelfHosted
    default: false
    type: boolean
  - name: LinuxVmImage
    default: ubuntu-20.04
    type: string
    values:
      - ubuntu-20.04
  - name: WindowsVmImage
    default: windows-2019
    type: string
    values:
      - windows-2019
jobs:
  - job: Finalizer
    condition: eq(parameters.SelfHosted, 'false')
    displayName: 'Update BUILD_NUMBER (finalizer)'
    timeoutInMinutes: 15
    pool:
      vmImage: $(parameters.LinuxVmImage)
    steps:
      - template: ../steps/dotnet.yml
      - template: ../steps/install-minvertool.yml
      - template: ../steps/minverversion-override.yml
      - template: ../steps/update-buildnumber.yml

  - job: Finalizer_SelfHosted
    condition: eq(parameters.SelfHosted, 'true')
    displayName: 'Update BUILD_NUMBER (finalizer, self-hosted)'
    timeoutInMinutes: 15
    pool:
      name: $(parameters.LinuxVmImage)
    steps:
      - template: ../steps/dotnet.yml
      - template: ../steps/install-minvertool.yml
      - template: ../steps/minverversion-override.yml
      - template: ../steps/update-buildnumber.yml