jobs:
  - job: 'Finalizer'
    displayName: 'Update BUILD_NUMBER (finalizer)'
    timeoutInMinutes: 15
    pool: 'ubuntu-20.04'
      # vmImage: 'ubuntu-20.04'
    steps:
      - template: ../steps/dotnet.yml
      - template: ../steps/install-minvertool.yml
      - template: ../steps/minverversion-override.yml
      - template: ../steps/update-buildnumber.yml