jobs:
  - job: 'Finalizer'
    displayName: 'Update BUILD_NUMBER (finalizer)'
    timeoutInMinutes: 15
    pool:
      ${{ if eq(variables.PipelinesSelfHosted, 'true') }}:
        name: $(PipelinesLinuxVmImage)
      ${{ if eq(variables.PipelinesSelfHosted, 'false') }}:
        vmImage: $(PipelinesLinuxVmImage)
    steps:
      - template: ../steps/dotnet.yml
      - template: ../steps/install-minvertool.yml
      - template: ../steps/minverversion-override.yml
      - template: ../steps/update-buildnumber.yml